url=https://practicetestautomation.com/practice-test-login/
browser=chrome
implicitWait=10
paralleExecution=false
mongo.uri=mongodb://localhost:27017
mongo.db=testAutomation
mongo.collection=testResults
